import data from './object-knowledge.json';
import type { Box } from './vision';

/*
 * What each detectable thing *is* to the people in a photo, from docs/OBJECT_ANALOGIES.md
 * (generated by scripts/build-object-knowledge.mjs from HICO-DET interactions + COCO families).
 * The engine uses it to recognise relations, sanity-check detections, map look-alikes between
 * shots, and transfer lessons between analogous objects.
 */

export type Schema = 'grasp' | 'wear' | 'ride' | 'seat' | 'table' | 'enclose' | 'companion' | 'fixture' | 'play';
type ObjectKnowledge = {
  family: string;
  animate: boolean;
  portable: boolean;
  sizeM: [number, number];
  placement: string;
  schemas: Schema[];
  verbs: string[];
  lookalikes: string[];
  analogues: { label: string; score: number }[];
};

const OBJECTS = data.objects as unknown as Record<string, ObjectKnowledge>;
const PERSON_HEIGHT_M = 1.65;

/** The attribute each schema contributes to a structured description (see memory.ts, physics.ts). */
export const OBJECT_SCHEMA_PREDICATES: [Schema, string][] = [
  ['grasp', 'graspable'], ['wear', 'wearable'], ['ride', 'rideable'], ['seat', 'seat'], ['table', 'table'],
  ['enclose', 'vehicle'], ['companion', 'animal'], ['fixture', 'fixture'], ['play', 'plaything'],
];

export const knows = (label: string) => label in OBJECTS;

/** Plural-ish display names of the closest analogues: things that play the same role. */
export const sameRole = (label: string) => (OBJECTS[label]?.analogues ?? []).filter((a) => a.score >= 0.5).map((a) => a.label);
export const has = (label: string, schema: Schema) => OBJECTS[label]?.schemas.includes(schema) ?? false;
export const isLookalike = (a: string, b: string) => a === b || (OBJECTS[a]?.lookalikes.includes(b) ?? false);

/**
 * How analogous two labels are, 0..1: identical 1; listed analogue (same relational role) by its
 * score; look-alike 0.5; same COCO family 0.3; otherwise 0.
 */
export function labelSimilarity(a: string, b: string) {
  if (a === b) return 1;
  const known = OBJECTS[a];
  if (!known || !OBJECTS[b]) return 0;
  const analogue = known.analogues.find((x) => x.label === b) ?? OBJECTS[b].analogues.find((x) => x.label === a);
  if (analogue) return analogue.score;
  if (isLookalike(a, b)) return 0.5;
  return known.family === OBJECTS[b].family ? 0.3 : 0;
}

type Detection = { label: string; score: number; box: Box };
export type Verdict = { keep: boolean; label: string; reason?: string };

/**
 * Common-sense check of one object detection against the people in the photo (people give the
 * scale and are what worn things must sit on). Returns whether to keep it and its best label.
 */
export function checkDetection(detection: Detection, people: { box: Box; shoulderY?: number; hipY?: number }[]): Verdict {
  const known = OBJECTS[detection.label];
  if (!known || detection.label === 'person') return { keep: true, label: detection.label };
  const { box } = detection;

  // Worn things must be on someone: inside a person's box, and a tie below the collar line.
  if (known.schemas.includes('wear') && !known.schemas.includes('ride')) {
    const wearer = people.find((p) => box.x + box.w / 2 > p.box.x && box.x + box.w / 2 < p.box.x + p.box.w && box.y + box.h / 2 > p.box.y && box.y + box.h / 2 < p.box.y + p.box.h);
    if (!wearer && detection.score < 0.6) return { keep: false, label: detection.label, reason: 'worn item not on anyone' };
    if (detection.label === 'tie' && wearer?.shoulderY !== undefined && wearer.hipY !== undefined) {
      const centre = box.y + box.h / 2;
      const torso = wearer.hipY - wearer.shoulderY;
      if (centre < wearer.shoulderY + torso * 0.05 && detection.score < 0.6) return { keep: false, label: 'tie', reason: 'at the collar, not a tie' };
    }
  }

  // Size against people standing at a similar depth (feet at a similar height in the frame).
  const bottom = box.y + box.h;
  const peers = people.filter((p) => Math.abs(p.box.y + p.box.h - bottom) < Math.max(p.box.h, box.h) * 0.35);
  if (peers.length) {
    const metresPerPixel = PERSON_HEIGHT_M / (peers.map((p) => p.box.h).sort((x, y) => x - y)[Math.floor(peers.length / 2)]);
    const sizeM = Math.max(box.w, box.h) * metresPerPixel;
    const fits = (label: string) => {
      const [low, high] = OBJECTS[label].sizeM;
      return sizeM >= low / 2.5 && sizeM <= high * 2.5;
    };
    if (!fits(detection.label)) {
      // Analogical re-recognition: among things it is commonly mistaken for, does one fit?
      const better = known.lookalikes.find((label) => OBJECTS[label] && fits(label));
      if (better && detection.score < 0.6) return { keep: true, label: better, reason: `${detection.label} is the wrong size; looks like a ${better}` };
      if (detection.score < 0.5) return { keep: false, label: detection.label, reason: 'implausible size' };
    }
  }
  return { keep: true, label: detection.label };
}
